In [120]:
import pandas as pd
from datetime import datetime

In [121]:
df = pd.read_csv('./data/spotify.csv')
df.head()

,Song,Artists,Weeks at no 1,Average_Streams (Millions),Date_Published,Date_Achieved
0,WAP,Cardi B,1.0,40.3,7 August 2020,20 August 2020
1,Savage Love (Laxed – Siren Beat),Jawsh 685,2.0,32.2,11 June 2020,6 August 2020
2,Cardigan,Taylor Swift,1.0,35.7,24 July 2020,30 July 2020
3,Rockstar,DaBaby,7.0,37.4,24 April 2020,4 June 2020
4,Rain on Me,Lady Gaga,1.0,41.6,22 May 2020,28 May 2020

In [122]:
df.describe(include='all')

,Song,Artists,Weeks at no 1,Average_Streams (Millions),Date_Published,Date_Achieved
count,68,66,68.000000,68.000000,67,67
unique,67,46,NaN,NaN,66,67
top,Rockstar,Drake,NaN,NaN,10 May 2019,20 August 2020
freq,2,4,NaN,NaN,2,1
mean,NaN,NaN,6.169118,31.441176,NaN,NaN
std,NaN,NaN,6.990596,14.045685,NaN,NaN
min,NaN,NaN,1.000000,5.200000,NaN,NaN
25%,NaN,NaN,1.000000,18.575000,NaN,NaN
50%,NaN,NaN,4.500000,34.900000,NaN,NaN
75%,NaN,NaN,8.000000,41.925000,NaN,NaN
max,NaN,NaN,43.700000,53.000000,NaN,NaN

In [123]:
list(df.columns)

['Song',
 'Artists',
 'Weeks at no 1',
 'Average_Streams (Millions)',
 'Date_Published',
 'Date_Achieved']

In [124]:
df[df['Weeks at no 1'] > 6]

,Song,Artists,Weeks at no 1,Average_Streams (Millions),Date_Published,Date_Achieved
3,Rockstar,DaBaby,7.0,37.4,24 April 2020,4 June 2020
6,Blinding Lights,The Weeknd,13.0,42.0,29 November 2019,27 February 2020
9,Dance Monkey,Tones and I,17.0,46.2,10 May 2019,17 October 2019
12,Señorita,Shawn Mendes,14.0,53.0,21 June 2019,27 June 2019
15,7 Rings,Ariana Grande,10.0,47.9,18 January 2019,24 January 2019
18,"Thank U, Next",Ariana Grande,8.0,44.2,3 November 2018,8 November 2018
23,In My Feelings,Drake,8.0,51.5,29 June 2018,12 July 2018
24,Nonstop,NaN,43.7,46.7,NaN,NaN
30,God's Plan,Drake,11.0,47.8,19 January 2018,25 January 2018
32,Rockstar,Post Malone,17.0,38.6,15 September 2017,21 September 2017
36,Despacito (Remix),Luis Fonsi,14.0,45.9,17 April 2017,27 April 2017
38,Shape of You,Ed Sheeran,14.0,51.9,6 January 2017,12 January 2017
41,Closer,The Chainsmokers,11.0,34.1,29 July 2016,1 September 2016
43,One Dance,Drake,14.0,39.8,5 April 2016,21 April 2016
44,Work,Rihanna,9.0,28.0,27 January 2016,18 February 2016
47,Sorry,NaN,28.8,23.9,24 October 2015,19 November 2015
49,What Do You Mean?,Justin Bieber,8.0,24.1,28 August 2015,3 September 2015
52,Lean On,Major Lazer,10.0,14.8,2 March 2015,4 June 2015
55,Uptown Funk,Mark Ronson,8.0,14.7,10 November 2014,11 January 2015
60,Rude,Magic!,8.0,9.0,11 October 2013,20 July 2014
61,Summer,Calvin Harris,10.0,8.6,14 March 2014,11 May 2014
62,Rather Be,Clean Bandit,7.0,8.2,17 January 2014,23 March 2014
65,The Monster,Eminem,8.0,7.6,29 October 2013,10 November 2013

## Top 5 trending

In [125]:
top5Trending = df['Weeks at no 1'].sort_values(ascending=False).head()
top5Trending

24    43.7
47    28.8
9     17.0
32    17.0
12    14.0
Name: Weeks at no 1, dtype: float64

In [126]:
df_top_5_trending = df[['Song', 'Weeks at no 1', 'Average_Streams (Millions)', 'Date_Published']]
df_top_5_trending['Average_Streams (Millions)'].sort_values(ascending=False)
df_top_5_trending['Song'].head()

0                                 WAP
1    Savage Love (Laxed – Siren Beat)
2                            Cardigan
3                            Rockstar
4                          Rain on Me
Name: Song, dtype: object

In [127]:
df['Date_Published'].dtype

dtype('O')

## Top 5 artists

In [128]:
df_top_artists = df.groupby('Artists').sum()

C:\Users\HP\AppData\Local\Temp\ipykernel_17576\2444019488.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_top_artists = df.groupby('Artists').sum()

In [129]:
df_top_artists['Average_Streams (Millions)'].sort_values(ascending=False).head()

Artists
Drake           179.8
Post Malone     148.5
The Weeknd      127.7
Ed Sheeran      105.9
Travis Scott     96.6
Name: Average_Streams (Millions), dtype: float64

## Replace NaN to current Date

In [130]:
df['Date_Published'].dtype

dtype('O')

In [134]:
df['Date_Published'] = df['Date_Published'].fillna(pd.Timestamp.today().strftime('%d %b %Y'))
df['Date_Achieved'] = df['Date_Achieved'].fillna(pd.Timestamp.today().strftime('%d %b %Y'))

In [133]:
df.iloc[1:40]

,Song,Artists,Weeks at no 1,Average_Streams (Millions),Date_Published,Date_Achieved
1,Savage Love (Laxed – Siren Beat),Jawsh 685,2.0,32.2,11 June 2020,6 August 2020
2,Cardigan,Taylor Swift,1.0,35.7,24 July 2020,30 July 2020
3,Rockstar,DaBaby,7.0,37.4,24 April 2020,4 June 2020
4,Rain on Me,Lady Gaga,1.0,41.6,22 May 2020,28 May 2020
5,The Scotts,Travis Scott,1.0,48.4,23 April 2020,30 April 2020
6,Blinding Lights,The Weeknd,13.0,42.0,29 November 2019,27 February 2020
7,The Box,Roddy Ricch,1.0,46.2,6 December 2019,13 February 2020
8,Lose You to Love Me,Selena Gomez,1.0,47.2,23 October 2019,31 October 2019
9,Dance Monkey,Tones and I,17.0,46.2,10 May 2019,17 October 2019
10,Highest in the Room,Travis Scott,1.0,48.2,4 October 2019,10 October 2019
11,Circles,Post Malone,1.0,43.4,30 August 2019,12 September 2019
12,Señorita,Shawn Mendes,14.0,53.0,21 June 2019,27 June 2019
13,I Don't Care,Ed Sheeran,6.0,44.0,10 May 2019,16 May 2019
14,Bad Guy,Billie Eilish,6.0,42.6,29 March 2019,4 April 2019
15,7 Rings,Ariana Grande,10.0,47.9,18 January 2019,24 January 2019
16,Sunflower,Post Malone,2.0,33.6,18 October 2018,17 January 2019
17,All I Want for Christmas Is You,Mariah Carey,1.0,39.6,1 November 1994,27 December 2018
18,"Thank U, Next",Ariana Grande,8.0,44.2,3 November 2018,8 November 2018
19,Mia,Bad Bunny,1.0,39.6,12 October 2018,18 October 2018
20,Taki Taki,DJ Snake,4.0,35.9,28 September 2018,4 October 2018
21,I Love It,Kanye West,3.0,32.9,7 September 2018,13 September 2018
22,Lucky You,Eminem,1.0,34.9,31 August 2018,6 September 2018
23,In My Feelings,Drake,8.0,51.5,29 June 2018,12 July 2018
24,Nonstop,NaN,43.7,46.7,04 Nov 2022,NaN
25,Sad!,XXXTentacion,2.0,35.8,2 March 2018,21 June 2018
26,This Is America,Childish Gambino,1.0,34.9,5 May 2018,21 May 2018
27,Better Now,Post Malone,6.0,32.9,27 April 2018,3 May 2018
28,Nice for What,Drake,2.0,40.7,6 April 2018,19 April 2018
29,Call Out My Name,The Weeknd,1.0,40.6,30 March 2018,5 April 2018
30,God's Plan,Drake,11.0,47.8,19 January 2018,25 January 2018
31,Havana,Camila Cabello,1.0,30.9,3 August 2017,18 January 2018
32,Rockstar,Post Malone,17.0,38.6,15 September 2017,21 September 2017
33,Too Good at Goodbyes,Sam Smith,1.0,30.7,8 September 2017,14 September 2017
34,Look What You Made Me Do,Taylor Swift,2.0,39.8,24 August 2017,31 August 2017
35,Mi Gente,J Balvin,4.0,32.1,30 June 2017,3 August 2017
36,Despacito (Remix),Luis Fonsi,14.0,45.9,17 April 2017,27 April 2017
37,Humble,Kendrick Lamar,1.0,41.4,30 March 2017,20 April 2017
38,Shape of You,Ed Sheeran,14.0,51.9,6 January 2017,12 January 2017
39,Starboy,The Weeknd,6.0,29.2,21 September 2016,1 December 2016

In [144]:
df['Weeks at no 1'].nunique()

16

In [ ]:
df.drop('Weeks at no 1')